version: '3.8'

services:
    php:
        container_name: php_container
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:8000
        depends_on:
            - db
        # entrypoint: >
        #     sh -c "sleep 10 && php artisan migrate --force"

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_auth_app
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            retries: 5
            timeout: 5s

    nginx:
        container_name: nginx_container
        image: nginx:alpine
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        # networks:
        #     - laravel-auth-appv1_laravel
        depends_on:
            - php

volumes:
    db_data:

networks:
  laravel-auth-appv1_laravel:
    external: true


